### ISSUE TITLE
D2_KSamplerノードのconditioning出力

### ISSUE THREAD

**Issue by abyss9999** [da2el-ai/D2-nodes-ComfyUI#1]
D2 KSamplerノードで使用したpositive_condとnegative_condを出力に追加できませんか？
Ultimate SD UpscaleにD2_KSamplerから直接繋げられるようにしたいです

**Comment by da2el-ai** [comment]
対応いたしました。
https://github.com/da2el-ai/D2-nodes-ComfyUI/commit/fa286338b0c12d886a9ce20ba94acbbedb2b51b6

**Comment by da2el-ai** [comment]
対応いたしました
https://github.com/da2el-ai/D2-nodes-ComfyUI/commit/fa286338b0c12d886a9ce20ba94acbbedb2b51b6
